language: node_js
node_js:
  - "node"
  - 4.1
  - 0.10

env: BROWSERS=firefox E2E_BROWSERS=Firefox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - chmod a+x scripts/private/test-all.sh
